import React from 'react';
import { X, Download, Share2, FileText, CheckCircle } from 'lucide-react';

const AARModal = ({ data, onClose }) => {
  if (!data) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleShare = () => {
    navigator.clipboard.writeText("https://aegis-ndma.gov.in/aar/report-8923");
    alert("Share link copied to clipboard: https://aegis-ndma.gov.in/aar/report-8923");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm print:bg-white print:relative print:z-auto print:block">
      <div className="bg-white text-black w-full max-w-4xl h-[90vh] rounded-lg shadow-2xl flex flex-col overflow-hidden print:w-full print:h-auto print:shadow-none print:rounded-none">
        
        {/* Header Actions - hidden in print */}
        <div className="bg-gray-100 p-4 flex justify-between items-center border-b border-gray-300 print:hidden">
          <div className="flex gap-3">
            <button onClick={handlePrint} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded shadow hover:bg-blue-700 transition font-sans">
              <Download size={16} /> Download PDF
            </button>
            <button onClick={handleShare} className="flex items-center gap-2 bg-gray-200 text-gray-800 px-4 py-2 rounded shadow hover:bg-gray-300 transition font-sans">
              <Share2 size={16} /> Share with NDMA
            </button>
          </div>
          <button onClick={onClose} className="text-gray-500 hover:text-red-500 transition p-1">
            <X size={24} />
          </button>
        </div>

        {/* Document Body */}
        <div className="p-10 overflow-y-auto flex-1 font-serif print:overflow-visible print:p-0 bg-white" id="aar-document">
          <div className="text-center mb-10 border-b-2 border-black pb-6">
            <h1 className="text-3xl font-bold uppercase tracking-widest mb-2 text-black">After-Action Report (AAR)</h1>
            <h2 className="text-xl text-gray-700 font-medium">National Disaster Management Authority Format</h2>
            <p className="text-sm text-gray-500 mt-2 font-sans">Generated by AEGIS AI Command Center | Date: {new Date().toLocaleDateString()}</p>
          </div>

          <div className="space-y-8">
            <section>
              <h3 className="text-xl font-bold bg-gray-100 p-2 mb-3 border-l-4 border-black uppercase flex items-center gap-2 text-black">
                <FileText size={20} /> 1. Executive Summary
              </h3>
              <p className="whitespace-pre-wrap leading-relaxed text-gray-800">{data.executive_summary}</p>
            </section>

            <section>
              <h3 className="text-xl font-bold bg-gray-100 p-2 mb-3 border-l-4 border-black uppercase flex items-center gap-2 text-black">
                <FileText size={20} /> 2. Incident Timeline
              </h3>
              <table className="w-full text-left border-collapse border border-gray-300">
                <thead>
                  <tr className="bg-gray-100 text-black">
                    <th className="border border-gray-300 p-2 w-1/4">Timestamp</th>
                    <th className="border border-gray-300 p-2 w-3/4">Event Description</th>
                  </tr>
                </thead>
                <tbody>
                  {data.incident_timeline?.map((item, idx) => (
                    <tr key={idx} className="hover:bg-gray-50 text-gray-800">
                      <td className="border border-gray-300 p-2 text-sm font-sans">{item.timestamp}</td>
                      <td className="border border-gray-300 p-2 text-sm">{item.event}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </section>

            <section>
              <h3 className="text-xl font-bold bg-gray-100 p-2 mb-3 border-l-4 border-black uppercase flex items-center gap-2 text-black">
                <FileText size={20} /> 3. Resource Deployment Analysis
              </h3>
              <p className="leading-relaxed text-gray-800">{data.resource_deployment_analysis}</p>
            </section>

            <section>
              <h3 className="text-xl font-bold bg-gray-100 p-2 mb-3 border-l-4 border-black uppercase flex items-center gap-2 text-black">
                <FileText size={20} /> 4. Response Time Performance
              </h3>
              <p className="leading-relaxed text-gray-800">{data.response_time_performance}</p>
            </section>

            <section>
              <h3 className="text-xl font-bold bg-gray-100 p-2 mb-3 border-l-4 border-black uppercase flex items-center gap-2 text-black">
                <FileText size={20} /> 5. AI Decision Quality Audit
              </h3>
              <p className="leading-relaxed text-gray-800">{data.decision_quality_audit}</p>
            </section>

            <section>
              <h3 className="text-xl font-bold bg-gray-100 p-2 mb-3 border-l-4 border-black uppercase flex items-center gap-2 text-black">
                <FileText size={20} /> 6. Golden Hour Performance
              </h3>
              <p className="leading-relaxed text-gray-800">{data.golden_hour_performance}</p>
            </section>

            <section className="print:break-inside-avoid">
              <h3 className="text-xl font-bold bg-gray-100 p-2 mb-3 border-l-4 border-black uppercase flex items-center gap-2 text-black">
                <FileText size={20} /> 7. Recommendations for Improvement
              </h3>
              <ul className="list-disc pl-6 space-y-2 text-gray-800">
                {data.recommendations?.map((rec, idx) => (
                  <li key={idx} className="leading-relaxed">{rec}</li>
                ))}
              </ul>
            </section>
            
            <div className="mt-12 pt-8 border-t border-gray-300 flex justify-between items-center text-gray-500 text-sm font-sans">
              <p>CONFIDENTIAL - INTERNAL NDMA USE ONLY</p>
              <div className="flex items-center gap-1">
                <CheckCircle size={16} className="text-green-600" /> AEGIS Automated Generation
              </div>
            </div>
          </div>
        </div>
      </div>

      <style dangerouslySetInnerHTML={{__html: `
        @media print {
          body * {
            visibility: hidden;
          }
          #aar-document, #aar-document * {
            visibility: visible;
          }
          #aar-document {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
        }
      `}} />
    </div>
  );
};

export default AARModal;
